# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JoyLi-aosunUxOi92E5nRpizM4zgm7wn
"""

import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)

print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

fahrenheit = (temperatures_w1 * 9/5) + 32

print("Temperature in Fahrenheit:")
print(fahrenheit)

print(temperatures_w1[:3])

print(temperatures_w1[-2:])

print(temperatures_w1[2:5])

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print(temperatures)

print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Number of Elements:", temperatures.size)

print("Week 1:", temperatures[0])

print("Week 2:", temperatures[1])

print("Week 1 Weekend:", temperatures[0, -2:])

print("Week 2 Weekend:", temperatures[1, -2:])

import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

print(marks.iloc[0])

print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

print(marks.iloc[2])

print(marks[marks > 90])

marks.loc['Rank1'] = 100

print(marks)

marks = marks.drop('Rank5')

print(marks)

cgpa = marks / 10

print(cgpa)

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

print(transactions)

print(transactions.head())

print(transactions.tail())

print(transactions.shape)

print(transactions.columns)

print(transactions.dtypes)

print(transactions[['ProductCategory', 'Amount']])

print(transactions.iloc[:, -3:])

print(transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
])

print(transactions['ProductCategory'].value_counts())

print(transactions['Region'].unique())

print(transactions.groupby('Region')['Amount'].mean())

transactions.loc[
    transactions['TransactionID'] == 102,
    'Amount'
] = 165

print(transactions)

transactions['Discount'] = transactions['Amount'] * 0.10

print(transactions)

transactions = transactions[
    transactions['TransactionID'] != 109
]

print(transactions)

transactions = transactions.drop(columns=['Discount'])

print(transactions)

